### ISSUE TITLE
Splynx Integration Bug

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#273] opened 2023-02-22 15:45 UTC
Originally posted by [ubun3t](https://github.com/ubun3t):

Hello, I'm testing the integration of Splynx and I'm having issues with data importing. The key downloadForTariffID[tariff_id] is giving an error and I'm not sure why.

I've modified the code to see what the function getTariffs returns to show information and the result is as follows:

def getTariffs(headers):
data = spylnxRequest("admin/tariffs/internet", headers)
tariff = []
downloadForTariffID = {}
uploadForTariffID = {}
for tariff in data:
tariffID = tariff['id']
speed_download = tariff['speed_download']
speed_upload = tariff['speed_upload']
downloadForTariffID[tariffID] = speed_download
uploadForTariffID[tariffID] = speed_upload
print("Tariffs: ", tariffID)
print("Download speeds: ", downloadForTariffID)
print("Upload speeds: ", uploadForTariffID)
return (tariff, downloadForTariffID, uploadForTariffID)

Output:

`Tariffs: 181

Download speeds: {'1': '7100', '13': '5100', '14': '12200', '15': '20480', '16': '30100', '17': '20100', '18': '15100', '19': '25100', '20': '35100', '21': '30100', '25': '20100', '27': '20100', '28': '12200', '30': '31000', '31': '50000', '34': '5100', '36': '20100', '37': '30100', '44': '30100', '45': '8200', '46': '15200', '48': '12200', '49': '12200', '50': '20200', '51': '20200', '56': '20100', '57': '20100', '58': '15100', '59': '20100', '60': '20100', '67': '18100', '68': '25100', '69': '35100', '70': '30100', '72': '5100', '74': '12100', '75': '20100', '76': '20100', '78': '30100', '80': '20100', '81': '3100', '83': '5100', '87': '12100', '88': '20100', '89': '30100', '91': '20100', '93': '7100', '94': '15100', '95': '35100', '96': '25100', '98': '35100', '99': '15100', '100': '25100', '101': '35100', '102': '30100', '103': '7100', '104': '10100', '105': '20100', '107': '7100', '108': '8100', '109': '35100', '110': '30100', '111': '8100', '112': '7100', '113': '15100', '114': '25100', '115': '30100', '116': '4100', '117': '35100', '118': '30100', '119': '25100', '120': '7100', '121': '15100', '122': '25100', '123': '30100', '124': '35100', '125': '7100', '126': '15100', '127': '25100', '128': '35100', '129': '30100', '130': '10100', '131': '20100', '132': '25100', '133': '8200', '134': '15200', '135': '7100', '136': '15100', '137': '25100', '138': '35100', '139': '30100', '140': '15100', '141': '15100', '142': '18100', '143': '1100', '144': '30100', '145': '15100', '146': '25100', '147': '30100', '148': '7100', '149': '35100', '150': '200100', '151': '15100', '152': '25100', '153': '30100', '154': '7100', '155': '35100', '156': '15100', '157': '30100', '158': '15100', '159': '100100', '160': '15100', '161': '7100', '162': '7100', '163': '18100', '164': '18100', '165': '600000', '166': '18100', '167': '25100', '168': '35100', '169': '30100', '170': '1', '171': '1', '172': '1', '173': '1', '174': '1', '175': '1', '176': '1', '177': '25100', '178': '25100', '179': '30100', '180': '3100', '181': '5100'}

Upload speeds: {'1': '1024', '13': '1024', '14': '2100', '15': '4096', '16': '6100', '17': '20100', '18': '2100', '19': '4100', '20': '6100', '21': '8100', '25': '20100', '27': '4100', '28': '2100', '30': '31000', '31': '20000', '34': '5100', '36': '4100', '37': '6100', '44': '20100', '45': '4100', '46': '7100', '48': '2100', '49': '2100', '50': '4100', '51': '4100', '56': '20100', '57': '20100', '58': '15100', '59': '20100', '60': '4100', '67': '2100', '68': '4100', '69': '6100', '70': '8100', '72': '1100', '74': '2100', '75': '4100', '76': '4100', '78': '6100', '80': '20100', '81': '1100', '83': '1100', '87': '2100', '88': '4100', '89': '6100', '91': '4100', '93': '1100', '94': '2100', '95': '8100', '96': '4100', '98': '6100', '99': '2100', '100': '4100', '101': '6100', '102': '8100', '103': '1100', '104': '1100', '105': '4100', '107': '3100', '108': '4100', '109': '6100', '110': '8100', '111': '4100', '112': '1100', '113': '2100', '114': '4100', '115': '8100', '116': '1100', '117': '6100', '118': '8100', '119': '4100', '120': '1100', '121': '2100', '122': '4100', '123': '8100', '124': '6100', '125': '1100', '126': '2100', '127': '4100', '128': '6100', '129': '8100', '130': '4100', '131': '5100', '132': '4100', '133': '4100', '134': '7100', '135': '1100', '136': '2100', '137': '4100', '138': '6100', '139': '8100', '140': '2100', '141': '2100', '142': '2100', '143': '512', '144': '8100', '145': '2100', '146': '4100', '147': '8100', '148': '1100', '149': '6100', '150': '40100', '151': '2100', '152': '4100', '153': '8100', '154': '1100', '155': '6100', '156': '2100', '157': '8100', '158': '2100', '159': '40100', '160': '2100', '161': '1100', '162': '1100', '163': '2100', '164': '2100', '165': '200000', '166': '2100', '167': '4100', '168': '6100', '169': '8100', '170': '1', '171': '1', '172': '1', '173': '1', '174': '1', '175': '1', '176': '1', '177': '4100', '178': '4100', '179': '8100', '180': '1100', '181': '1100'}
Traceback (most recent call last):
File "/opt/libreqos/src/integrationSplynx.py", line 130, in
importFromSplynx()
File "/opt/libreqos/src/integrationSplynx.py", line 127, in importFromSplynx
createShaper()
File "/opt/libreqos/src/integrationSplynx.py", line 87, in createShaper
download=downloadForTariffID[tariff_id],
KeyError: '2' `

Is it normal this data output? Or should it only display the configured upload and download rates for each found tariff ID?"

Thanks in advance.

**Comment by rchac** [comment] 2023-02-22 15:49
@ubun3t downloadForTariffID is a dictionary, so that seems correct. But yes there's some issue here. Do you have a tariff with id 2 in Splynx?

**Comment by ubun3t** [comment] 2023-02-22 17:29
Hi @rchac , no, the tariff with ID 2 does not exist. The ids are 1, 13-181,

**Comment by rchac** [comment] 2023-02-22 17:48
@ubun3t Interesting. Did it exist previously at any point? I'm wondering if a tariff plan was deleted at some point, but the id remains on the back end of the Splynx API?

**Comment by ubun3t** [comment] 2023-02-22 17:59
Sure, at some point in the past, there were IDs 2 to 12, but they were deleted. However, according to the code information being read, it should only read the current IDs present.

On another note, it is possible to read customer information, and it is likely that some of them have tariff_id 2 or the deleted IDs. Perhaps the function that reads the customer information should only read customers with 'status!=disabled'

**Comment by rchac** [comment] 2023-02-22 18:05
I made a test branch you can try to see if [this version of integrationSplynx.py](https://github.com/LibreQoE/LibreQoS/blob/attemptSplynxFix/src/integrationSplynx.py) helps.

**Comment by ubun3t** [comment] 2023-02-22 19:38
Firts the variable "status" on line 71 is not defined. I have changed to : 
if customerJson['status'] != 'disabled':

But the error persist : 

Traceback (most recent call last):
File "/opt/libreqos/src/integrationSplynx.py", line 130, in
importFromSplynx()
File "/opt/libreqos/src/integrationSplynx.py", line 127, in importFromSplynx
createShaper()
File "/opt/libreqos/src/integrationSplynx.py", line 87, in createShaper
download=downloadForTariffID[tariff_id],
KeyError: '2' `

**Comment by rchac** [comment] 2023-02-22 20:09
So if I'm understanding correctly, your Splynx instance has some plans which are 'active' but correspond to a tariff which no longer exists. I think you would need to associate those plans with some existing tariff to be able to use this integration.

**Comment by lukastribus** [comment] 2023-02-22 20:42
In Splynx, plans can exist or not.
Customers on other hand can be in all kinds of inactive states, like archived, disabled or stopped.

Customer in inactive or archived status that are long gone can obviously reference plans that no longer exist.

LibreQoS should really ignore all customers that are no in active state, and *not* try to resolve plans for those.

**Comment by rchac** [comment] 2023-02-22 20:48
@lukastribus Thank you for explaining. @ubun3t Does [this](https://github.com/LibreQoE/LibreQoS/blob/attemptSplynxFix/src/integrationSplynx.py) help?

**Comment by lukastribus** [comment] 2023-02-22 20:53
Clarification:

What I meant was a customer service --> https://docs.splynx.com/customer_management/customer_services

This is different than the customer itself --> https://docs.splynx.com/customer_management/customer_information

I'd guess that LibreQoS needs to access a customer service and not the customer itself.

**Comment by mwangi-kiboi** [comment] 2023-02-27 14:33
@rchac 
We have:-
1. Tariff ->>Internet Status available = (Active, Disabled/Archived)
2.  Customers - Status available = (New, Active, Blocked, Inactive)
3. Customer services - Status available = (Pending, Active, Stopped, Disabled, Archived)

@lukastribus says any status reading Inactive, disabled, stopped, or archived should be skipped in your script, be it tariff, customer, or customer services. The script would be more **productive** in handling active tariffs, customers, or tariffs.

**Comment by dtaht** [comment] 2023-02-27 16:39
I am kind of at the point here where suggesting a few command line options might be helpful. 

How should this API look like to these different folk?

**Comment by blongwe** [comment] 2023-02-27 21:37
I now seem to be running into the same error as others here
Fetching data from Spylnx
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:1015: InsecureRequestWarning: Unverified HTTPS request is being made to host 'splynx.*****.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 128, in <module>
    importFromSplynx()
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 125, in importFromSplynx
    createShaper()
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 67, in createShaper
    tariff, downloadForTariffID, uploadForTariffID = getTariffs(headers)
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 30, in getTariffs
    tariffID = tariff['id']
TypeError: string indices must be integers

**Comment by blongwe** [comment] 2023-02-27 22:04
Above issue sorted. Now I'm having the same key error due to missing tariff plan, error below:
  warnings.warn(
Traceback (most recent call last):
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 129, in <module>
    importFromSplynx()
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 126, in importFromSplynx
    createShaper()
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 86, in createShaper
    download=downloadForTariffID[tariff_id],
KeyError: '9'

**Comment by blongwe** [comment] 2023-02-27 22:26
Found a workaround. Went into Splynx SQL backend and switched the flag that showed a plan as deleted from '1' to '0' for all the affected plans. Now the Shaper has run successfuly!

**Comment by rchac** [comment] 2023-02-27 23:58
That's awesome! Nice troubleshooting :) To reduce future headache, the new ```if customerJson['status'] == 'active':``` check is now included on both v1.3 and v1.4.

**Comment by mwangi-kiboi** [comment] 2023-03-01 10:45
Tested the new file (https://github.com/LibreQoE/LibreQoS/blob/attemptSplynxFix/src/integrationSplynx.py) and still hitting the same error. Should I got the manual way to the splynx db?

`@libreqos:/opt/libreqos/src$ python3 integrationSplynx.py
Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Fetching data from Spylnx
Traceback (most recent call last):
  File "/opt/libreqos/src/integrationSplynx.py", line 128, in <module>
    importFromSplynx()
  File "/opt/libreqos/src/integrationSplynx.py", line 125, in importFromSplynx
    createShaper()
  File "/opt/libreqos/src/integrationSplynx.py", line 67, in createShaper
    tariff, downloadForTariffID, uploadForTariffID = getTariffs(headers)
  File "/opt/libreqos/src/integrationSplynx.py", line 30, in getTariffs
    tariffID = tariff['id']
TypeError: string indices must be integers
`

**Comment by ubun3t** [comment] 2023-03-01 11:00
@mwangi-kiboi what version you have installed? I see those errors on 4.1 demo server

**Comment by mwangi-kiboi** [comment] 2023-03-01 11:34
LibreQoS v1.4 (Alpha)

**Comment by ubun3t** [comment] 2023-03-01 12:03
I mean Splynx version. I only see this error when I try to get tariffs from 4.1.x

**Comment by mwangi-kiboi** [comment] 2023-03-01 12:15
@ubun3t yes Splynx 4.0.21155

**Comment by rchac** [comment] 2023-03-01 14:29
> Tested the new file (https://github.com/LibreQoE/LibreQoS/blob/attemptSplynxFix/src/integrationSplynx.py) and still hitting the same error. Should I got the manual way to the splynx db?
> 
> `@libreqos:/opt/libreqos/src$ python3 integrationSplynx.py Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] Fetching data from Spylnx Traceback (most recent call last): File "/opt/libreqos/src/integrationSplynx.py", line 128, in <module> importFromSplynx() File "/opt/libreqos/src/integrationSplynx.py", line 125, in importFromSplynx createShaper() File "/opt/libreqos/src/integrationSplynx.py", line 67, in createShaper tariff, downloadForTariffID, uploadForTariffID = getTariffs(headers) File "/opt/libreqos/src/integrationSplynx.py", line 30, in getTariffs tariffID = tariff['id'] TypeError: string indices must be integers `

You can use the regular branch. The fix was applied to v1.4. I'm pretty sure you're receiving an text error response from Splynx due to an authentication error. Just before tariffID = tariff['id'] (line 30) you can add print(tariff) to show this. The Splynx Integration uses Basic authentication. For using this type of authentication, please make sure you enable [Unsecure access](https://splynx.docs.apiary.io/#introduction/authentication) in your Splynx API key settings. Also the Splynx API key should be granted access to the necessary permissions.

**Comment by mwangi-kiboi** [comment] 2023-03-01 22:57
Got a step a head after allowing **"Unsecure access"**

` 'Gsa Home Fiber 10Mbps', 'service_name': 'Gsa Home Fiber 10Mbps', 'price': '3450.0000', 'billing_days_count': None, 'with_vat': '1', 'vat_percent': '0.0000', 'available_for
_services': '1', 'update_service_price': '0', 'update_service_name': '0', 'force_update_service_price': None, 'force_update_service_name': None, 'partners_ids': [5], 'billin
g_types': ['prepaid_monthly', 'recurring'], 'custom_period': 0, 'transaction_category_id': '0', 'updated_at': '2023-01-25 20:57:00', 'additional_attributes': {'available_whe
n_register_by_social_network': '0', 'iplook_apn_template_id': '', 'iplook_qci_level': '3', 'iplook_subscriber_template_name': ''}}
Traceback (most recent call last):
  File "/opt/libreqos/src/integrationSplynx.py", line 129, in <module>
    importFromSplynx()
  File "/opt/libreqos/src/integrationSplynx.py", line 126, in importFromSplynx
    createShaper()
  File "/opt/libreqos/src/integrationSplynx.py", line 86, in createShaper
    download=downloadForTariffID[tariff_id],
KeyError: '1'
`

**Comment by rchac** [comment] 2023-03-01 23:44
Is "Home Fiber 10Mbps" a plan that has since been deleted or disabled in Splynx?

**Comment by mwangi-kiboi** [comment] 2023-03-01 23:57
No, but had some tariffs deleted. Had to amend in the splynx Db and the shaper Run

`"Circuit ID","Circuit Name","Device ID","Device Name","Parent Node","MAC","IPv4","IPv6","Download Min","Upload Min","Download Max","Upload Max","Comment"
"c_1_s_1039","Moi Nairobi 00100","c_1_s_1039_d1039","Free Home Acc 100Mbps","","","","","99","99","102","102",""
"c_1_s_1076","Moi Nairobi 00100","c_1_s_1076_d1076","Business 15Mbps","","","","","14","14","15","15",""
"c_1_s_2592","Moi Nairobi 00100","c_1_s_2592_d2592","Free Home Acc 100Mbps","","","","","99","99","102","102",""`

1. Reportedly mine didn't pick up ipv4 assigned to the service.
2. It also shapes disabled or archived services see below
![libreqos](https://user-images.githubusercontent.com/100774208/222294071-89173d72-65bb-4e60-8972-cc33e37f4dc6.png)

**Comment by rchac** [comment] 2023-03-02 00:52
Could you please check if [this commit](https://github.com/LibreQoE/LibreQoS/commit/eb02c9568844ba9a98dfe3336735eb559af910d3) helps?

**Comment by mwangi-kiboi** [comment] 2023-03-02 01:40
@rchac '1' - Permanent IP (from Static IPs)

**Comment by rchac** [comment] 2023-03-02 02:34
Ok I made a change that *might* help. Let me know. https://github.com/LibreQoE/LibreQoS/blob/main/src/integrationSplynx.py

**Comment by mwangi-kiboi** [comment] 2023-03-02 16:51
@rchac it picks the ip but the io of the concentrator/Bras instead of the ipv4 in customer service.
Nb I have # the IP info
`@libreqos:/opt/libreqos/src$ cat  ShapedDevices.csv
"Circuit ID","Circuit Name","Device ID","Device Name","Parent Node","MAC","IPv4","IPv6","Download Min","Upload Min","Download Max","Upload Max","Comment"
"c_1_s_1039","Moi Nairobi 00100","c_1_s_1039_d1039","Free Home Acc 100Mbps","","","102.xx.22x.2","","99","99","102","102",""
"c_1_s_2592","Moi Nairobi 00100","c_1_s_2592_d2592","Free Home Acc 100Mbps","","","102.xx.22x.2","","99","99","102","102",""
"c_1_s_6106","Moi Nairobi 00100","c_1_s_6106_d6106","Free Home Acc 100Mbps","","","102.xx.22x.2","","99","99","102","102",""
"c_1_s_6107","Moi Nairobi 00100","c_1_s_6107_d6107","3Mbps Free Service","","","102.xx.22x.2","","2","2","3","3",""
`

**Comment by rchac** [comment] 2023-03-02 17:25
Strange. I'm having a hard time identifying the source of the IPv4 shown in the GUI's customer service field. If it's coming from [customer service](https://splynx.docs.apiary.io/#reference/services/internet-services-collection/list-all-customer-services) in the API, it should be returning the ipv4. Instead it returns blank.

In the latest commit, it will print the whole data structure of the customer service. Could you try the latest commit and see if the output of ```python3 integrationSplynx.py``` shows what number corresponds to "taking_ipv4"? If it's 3 that may explain why this is happening.

**Comment by mwangi-kiboi** [comment] 2023-03-02 18:07
@rchac here is a sample output for 3 clients.

`{'type': 'internet', 'top_up_tariff_id': None, 'router_id': '13', 'login': 'AFRIQ3261-Shugri', 'password': '729kbMjp', 'sector_id': '0', **'taking_ipv4': '1', 'ipv4': '102.xxx.xxx.140', 'ipv4_pool_id': '0',** 'taking_ipv6': '0', 'ipv6': '', 'ipv6_pool_id': '0', 'mac': '', 'port_id': '', 'ipv4_route': '', 'ipv6_delegated': '', 'parent_id': '0', 'customer_id': '3261', 'tariff_id': '87', 'bundle_service_id': '0', 'description': 'Home Fiber 8Mbps', 'quantity': '1', 'unit': '', 'unit_price': '2900.0000', 'start_date': '2023-03-01', 'end_date': '0000-00-00', 'discount': '0', 'discount_value': '0.0000', 'discount_type': 'percent', 'discount_start_date': '0000-00-00', 'discount_end_date': '0000-00-00', 'discount_text': '', 'status': 'active', 'status_new': '', 'period': '-1', 'id': '7232', 'additional_attributes': {'iplook_default_apn': '0', 'iplook_service_imsi': ''}, 'geo': {'address': 'BULA-SHEIKH, Garissa, 254', 'marker': '-0.451695, 39.637142'}}
{'type': 'internet', 'top_up_tariff_id': None, 'router_id': '33', 'login': 'AFRIQ3263-Fatuma', 'password': 'fSZu4zOk', 'sector_id': '0', **'taking_ipv4': '1', 'ipv4': '102.xxx.xxx.4', 'ipv4_pool_id': '0',** 'taking_ipv6': '0', 'ipv6': '', 'ipv6_pool_id': '0', 'mac': '', 'port_id': '', 'ipv4_route': '', 'ipv6_delegated': '', 'parent_id': '0', 'customer_id': '3263', 'tariff_id': '110', 'bundle_service_id': '0', 'description': 'Home Microwave 6Mbps', 'quantity': '1', 'unit': '', 'unit_price': '3450.0000', 'start_date': '2023-03-02', 'end_date': '0000-00-00', 'discount': '0', 'discount_value': '0.0000', 'discount_type': 'percent', 'discount_start_date': '0000-00-00', 'discount_end_date': '0000-00-00', 'discount_text': '', 'status': 'active', 'status_new': '', 'period': '-1', 'id': '7243', 'additional_attributes': {'iplook_default_apn': '0', 'iplook_service_imsi': ''}, 'geo': {'address': 'BULA-MPYA, Mandera, 254', 'marker': None}}
{'type': 'internet', 'top_up_tariff_id': None, 'router_id': '1', 'login': 'AFRIQ3264-Daniel', 'password': 'wazVjB6P', 'sector_id': '0', **'taking_ipv4': '1', 'ipv4': '102.xx.xxx.13', 'ipv4_pool_id': '0',** 'taking_ipv6': '0', 'ipv6': '', 'ipv6_pool_id': '0', 'mac': '', 'port_id': '', 'ipv4_route': '', 'ipv6_delegated': '', 'parent_id': '0', 'customer_id': '3264', 'tariff_id': '49', 'bundle_service_id': '0', 'description': 'Home Fiber 15', 'quantity': '1', 'unit': '', 'unit_price': '2900.0000', 'start_date': '2023-03-02', 'end_date': '0000-00-00', 'discount': '0', 'discount_value': '0.0000', 'discount_type': 'percent', 'discount_start_date': '0000-00-00', 'discount_end_date': '0000-00-00', 'discount_text': '', 'status': 'active', 'status_new': '', 'period': '-1', 'id': '7249', 'additional_attributes': {'iplook_default_apn': '0', 'iplook_service_imsi': ''}, 'geo': {'address': 'MUSINDI-ROAD, Nairobi, 254', 'marker': '-1.277901, 36.828316'}}
network.json already exists. Leaving in-place.
`

**Comment by rchac** [comment] 2023-03-03 00:08
So for example, for customer id 3263, is the correct ipv4 102.xxx.xxx.4?

**Comment by mwangi-kiboi** [comment] 2023-03-03 04:07
Yes it is.

**Comment by rchac** [comment] 2023-03-03 04:23
Does this latest change help produce a complete ShapedDevices.csv file? i tried seeing if your instance is returning strings for the taking_ipv4 field. https://github.com/LibreQoE/LibreQoS/blob/main/src/integrationSplynx.py

**Comment by mwangi-kiboi** [comment] 2023-03-04 00:42
@rchac Tested the lastest file and got to this

`@libreqos:/opt/libreqos/src$ python3 integrationSplynx.py
Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Fetching data from Spylnx
Traceback (most recent call last):
  File "/opt/libreqos/src/integrationSplynx.py", line 138, in <module>
    importFromSplynx()
  File "/opt/libreqos/src/integrationSplynx.py", line 135, in importFromSplynx
    createShaper()
  File "/opt/libreqos/src/integrationSplynx.py", line 100, in createShaper
    ipv4 = ipForRouter[routerID]
KeyError: '0'
`

**Comment by rchac** [comment] 2023-03-04 01:31
@mwangi-kiboi Made additional changes so we can try to see what client is causing this. It will now print a warning if that happens, along with the client id. https://github.com/LibreQoE/LibreQoS/blob/main/src/integrationSplynx.py

**Comment by mwangi-kiboi** [comment] 2023-03-04 02:21
@rchac I had a client **986** with two active services. 1 has a router and ipv4 assigned but the other has no router and no ipv4. But eventually, it built the **ShapedDevices.csv**

`@libreqos:/opt/libreqos/src$ python3 integrationSplynx.py
Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Fetching data from Spylnx
Router IPs found: 39
/opt/libreqos/src/integrationSplynx.py:140: UserWarning: taking_ipv4 was 0 for client c_986_s_2998 but router ID was not found in ipForRouter
  createShaper()
`
Waiting for a second run and share the outcome

**Comment by mwangi-kiboi** [comment] 2023-03-04 02:34
@rchac all seems ok now 

`@libreqos:/opt/libreqos/src$ python3 integrationSplynx.py
Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Fetching data from Spylnx
Router IPs found: 39
@libreqos:/opt/libreqos/src$
`

**Comment by mwangi-kiboi** [comment] 2023-03-04 02:37
@rchac jus

@rchac 
![image](https://user-images.githubusercontent.com/100774208/222871465-ba29e51a-7e70-49d2-ba92-c1cccad59e88.png)

At the **Circuit name**, I see it fetches the customer Address, **Customer name** would be of much more help than the address, then the **Device Name** picks up Tariff/service name not sure what it is meant for.

**Comment by rchac** [comment] 2023-03-04 02:53
Ok I changed Device Name to show the device ID instead of the tariff name.
Regarding the circuit name, I agree that customer name is more useful. We will have to either make a toggle option or change the format of ShapedDevices.csv to include a Customer Name field. Will talk to team about this.

**Comment by rchac** [comment] 2023-03-04 03:43
@mwangi-kiboi With [this change](https://github.com/LibreQoE/LibreQoS/pull/278) you can now use these lines in ispConfig.py to set Customer Name as the Circuit Name:
```
# Use Customer Name or Address as Circuit Name
circuitNameUseAddress = False
```

**Comment by mwangi-kiboi** [comment] 2023-03-04 10:48
@rchac tried it but still pulls address
![image](https://user-images.githubusercontent.com/100774208/222895778-3a8b997e-6404-4e55-beda-c1eb17f0c30b.png)

**Comment by rchac** [comment] 2023-03-04 12:53
@mwangi-kiboi Other files were changed. You'd need to do a git pull for it to make an effect.

**Comment by blongwe** [comment] 2023-03-04 16:39
I will also try this update as we now have it running inline

**Comment by rchac** [comment] 2023-03-04 17:13
@blongwe Awesome. Thank you! Hope it's working alright so far.

**Comment by blongwe** [comment] 2023-03-04 19:59
After the pull I'm gettng the following error when  try to restart LibreQOS

LibreQoS.service

     Loaded: loaded (/etc/systemd/system/LibreQoS.service; enabled; vendor
preset: enabled)

     Active: failed (Result: exit-code) since Sat 2023-03-04 19:57:14 UTC;
5s ago

    Process: 101685 ExecStart=/usr/bin/python3
/home/devops/LibreQoS/src/scheduler.py (code=exited, status=1/FAILURE)

    Process: 101686 ExecStopPost=/bin/bash -c /usr/bin/python3
/home/devops/LibreQoS/src/LibreQoS.py --clearrules (code=exited,
status=1/FAILURE)

   Main PID: 101685 (code=exited, status=1/FAILURE)

        CPU: 125ms


Mar 04 19:57:14 libreqos systemd[1]: LibreQoS.service: Scheduled restart
job, restart counter is at 5.

Mar 04 19:57:14 libreqos systemd[1]: Stopped LibreQoS.service.

Mar 04 19:57:14 libreqos systemd[1]: LibreQoS.service: Start request
repeated too quickly.

Mar 04 19:57:14 libreqos systemd[1]: LibreQoS.service: Failed with result
'exit-code'.

Mar 04 19:57:14 libreqos systemd[1]: Failed to start LibreQoS.service.

**Comment by blongwe** [comment] 2023-03-04 20:05
This seems to be the error:

***@***.***:~/LibreQoS/src$ sudo ./LibreQoS.py

Running Python Version 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

Traceback (most recent call last):

  File "/home/devops/LibreQoS/src/./LibreQoS.py", line 27, in <module>

    from liblqos_python import is_lqosd_alive, clear_ip_mappings,
delete_ip_mapping, validate_shaped_devices, \

ModuleNotFoundError: No module named 'liblqos_python'

**Comment by blongwe** [comment] 2023-03-04 20:11
> @blongwe Awesome. Thank you! Hope it's working alright so far.

After git pull I'm getting an error 

No module name 'liblqos_python'

**Comment by dtaht** [comment] 2023-03-05 03:59
did we manage to fix this in the chat?

**Comment by blongwe** [comment] 2023-03-05 05:07
Yes - problem was trying to run the new integrationSplynx.py on v1.3

Changing to v1.4 sorted it

**Closed** 2023-03-05 06:31 UTC
Labels: bug

**Comment by mwangi-kiboi** [comment] 2023-03-05 13:27
@rchac did git pull but got errors on trying to compile as below, what did I miss

`@libreqos:/opt/libreqos/src$ cd rust
cargo build --all
   Compiling lqos_sys v0.1.0 (/opt/libreqos/src/rust/lqos_sys)
   Compiling rocket v0.5.0-rc.2
   Compiling async-compression v0.3.15
   Compiling env_logger v0.10.0
The following warnings were emitted during compilation:

warning: [bpf skel] WARNING: bpftool not found for kernel 5.15.0-67

error: failed to run custom build command for `lqos_sys v0.1.0 (/opt/libreqos/src/rust/lqos_sys)`

Caused by:
  process didn't exit successfully: `/opt/libreqos/src/rust/target/debug/build/lqos_sys-db2fb4d067912bc7/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=[bpf skel] WARNING: bpftool not found for kernel 5.15.0-67

    You may need to install the following packages for this specific kernel:
      linux-tools-5.15.0-67-generic
      linux-cloud-tools-5.15.0-67-generic

    You may also want to install one of the following packages to keep up to date:
      linux-tools-generic
      linux-cloud-tools-generic


  --- stderr
  thread 'main' panicked at 'In file included from wrapper.c:1:
  ./wrapper.h:10:8: error: unknown type name '__u64'
  extern __u64 max_tracker_ips();
         ^
  wrapper.c:5:12: warning: implicit declaration of function 'lqos_kern__open' is invalid in C99 [-Wimplicit-function-declaration]
      return lqos_kern__open();
             ^
  wrapper.c:5:12: warning: incompatible integer to pointer conversion returning 'int' from a function with result type 'struct lqos_kern *' [-Wint-conversion]
      return lqos_kern__open();
             ^~~~~~~~~~~~~~~~~
  wrapper.c:9:12: warning: implicit declaration of function 'lqos_kern__load' is invalid in C99 [-Wimplicit-function-declaration]
      return lqos_kern__load(skel);
             ^
  wrapper.c:12:8: error: unknown type name '__u64'
  extern __u64 max_tracker_ips() {
         ^
  wrapper.c:16:33: warning: declaration of 'enum libbpf_print_level' will not be visible outside of this function [-Wvisibility]
  static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
                                  ^
  wrapper.c:16:79: error: unknown type name 'va_list'
  static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
                                                                                ^
  wrapper.c:16:52: error: variable has incomplete type 'enum libbpf_print_level'
  static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
                                                     ^
  wrapper.c:16:33: note: forward declaration of 'enum libbpf_print_level'
  static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
                                  ^
  wrapper.c:22:2: warning: implicit declaration of function 'libbpf_set_print' is invalid in C99 [-Wimplicit-function-declaration]
          libbpf_set_print(libbpf_print_fn);
          ^
  In file included from wrapper.c:32:
  /usr/include/bpf/libbpf.h:59:30: error: conflicting types for 'libbpf_set_print'
  LIBBPF_API libbpf_print_fn_t libbpf_set_print(libbpf_print_fn_t fn);
                               ^
  wrapper.c:22:2: note: previous implicit declaration is here
          libbpf_set_print(libbpf_print_fn);
          ^
  wrapper.c:104:26: error: incomplete definition of type 'struct lqos_kern'
          fd = bpf_program__fd(obj->progs.tc_iphash_to_cpu);
                               ~~~^
  ./wrapper.h:4:15: note: forward declaration of 'struct lqos_kern'
  extern struct lqos_kern * lqos_kern_open();
                ^
  wrapper.c:107:10: error: use of undeclared identifier 'ENOENT'
                  err = -ENOENT;
                         ^
  wrapper.c:115:21: error: use of undeclared identifier 'EEXIST'
          if (err && err != -EEXIST) {
                             ^
  wrapper.c:120:25: error: use of undeclared identifier 'EEXIST'
          if (verbose && err == -EEXIST) {
                                 ^
  wrapper.c:210:26: error: incomplete definition of type 'struct lqos_kern'
          fd = bpf_program__fd(obj->progs.bifrost);
                               ~~~^
  ./wrapper.h:4:15: note: forward declaration of 'struct lqos_kern'
  extern struct lqos_kern * lqos_kern_open();
                ^
  wrapper.c:213:10: error: use of undeclared identifier 'ENOENT'
                  err = -ENOENT;
                         ^
  wrapper.c:221:21: error: use of undeclared identifier 'EEXIST'
          if (err && err != -EEXIST) {
                             ^
  wrapper.c:226:25: error: use of undeclared identifier 'EEXIST'
          if (verbose && err == -EEXIST) {
                                 ^
  wrapper.c:262:55: error: use of undeclared identifier 'errno'
                  printf("Failed to open %s: '%s'!\n", fcpu, strerror(errno));
                                                                      ^
  wrapper.c:263:3: warning: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Wimplicit-function-declaration]
                  exit(1);
                  ^
  wrapper.c:263:3: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
  wrapper.c:309:20: error: use of undeclared identifier 'errno'
                                  __func__, cpu, errno, strerror(errno));
                                                 ^
  wrapper.c:309:36: error: use of undeclared identifier 'errno'
                                  __func__, cpu, errno, strerror(errno));
                                                                 ^
  6 warnings and 16 errors generated.
  ', lqos_sys/build.rs:17:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
`

@blongwe was this same experience on your end?

**Comment by thebracket** [comment] 2023-03-05 13:31
sudo apt install linux-tools-5.15.0-67-generic

And then build. That should fix it.
